/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Address;
import Model.ContactInfo;
import Model.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author jeelkanzaria
 */
public class MainJframe extends javax.swing.JFrame {

    /**
     * Creates new form MainJframe
     */
    Person Person;
    public MainJframe() {
        initComponents();
       this.Person = new Person(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        NUID = new javax.swing.JLabel();
        Firstname = new javax.swing.JLabel();
        Lastname = new javax.swing.JLabel();
        Collegename = new javax.swing.JLabel();
        Personalphone = new javax.swing.JLabel();
        PersonalEmail = new javax.swing.JLabel();
        Officephone = new javax.swing.JLabel();
        Officeemail = new javax.swing.JLabel();
        Currstreet = new javax.swing.JLabel();
        Currapt = new javax.swing.JLabel();
        Currcity = new javax.swing.JLabel();
        Currzip = new javax.swing.JLabel();
        Peraddr = new javax.swing.JLabel();
        Currentaddr = new javax.swing.JLabel();
        Perstreet = new javax.swing.JLabel();
        Permapt = new javax.swing.JLabel();
        Permcity = new javax.swing.JLabel();
        Permzip = new javax.swing.JLabel();
        Savebutton = new javax.swing.JButton();
        textNUID = new javax.swing.JTextField();
        textfirstname = new javax.swing.JTextField();
        textlastname = new javax.swing.JTextField();
        textcollgname = new javax.swing.JTextField();
        textpersphone = new javax.swing.JTextField();
        textpersemail = new javax.swing.JTextField();
        textcurrstreet = new javax.swing.JTextField();
        textcurrapt = new javax.swing.JTextField();
        textcurrcity = new javax.swing.JTextField();
        textcurrzip = new javax.swing.JTextField();
        textofficephone = new javax.swing.JTextField();
        textofficeemail = new javax.swing.JTextField();
        textpermstreet = new javax.swing.JTextField();
        textpermapt = new javax.swing.JTextField();
        textpermcity = new javax.swing.JTextField();
        textpermzip = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        viewnuid = new javax.swing.JLabel();
        viewfname = new javax.swing.JLabel();
        viewlname = new javax.swing.JLabel();
        viewcolname = new javax.swing.JLabel();
        viewpphone = new javax.swing.JLabel();
        viewpemail = new javax.swing.JLabel();
        ophone = new javax.swing.JLabel();
        viewoemail = new javax.swing.JLabel();
        viewcstreet = new javax.swing.JLabel();
        viewcapt = new javax.swing.JLabel();
        viewccity = new javax.swing.JLabel();
        viewczip = new javax.swing.JLabel();
        viewpstreet = new javax.swing.JLabel();
        viewpapt = new javax.swing.JLabel();
        viewpcity = new javax.swing.JLabel();
        viewpzip = new javax.swing.JLabel();

        jLabel16.setText("jLabel16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        NUID.setText("NUID");

        Firstname.setText("First Name");

        Lastname.setText("Last Name");

        Collegename.setText("College Name");

        Personalphone.setText("Personal Phone");

        PersonalEmail.setText("Personal Email");

        Officephone.setText("Office Phone");

        Officeemail.setText("Office Email");

        Currstreet.setText("Street");

        Currapt.setText("Apartment No");

        Currcity.setText("City/State");

        Currzip.setText("Zip Code");

        Peraddr.setText("Permanent Address:");

        Currentaddr.setText("Current Address:");

        Perstreet.setText("Street");

        Permapt.setText("Apartment No");

        Permcity.setText("City/State");

        Permzip.setText("Zip Code");

        Savebutton.setText("SAVE");
        Savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebuttonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        viewnuid.setText("jLabel1");

        viewfname.setText("jLabel2");

        viewlname.setText("jLabel1");

        viewcolname.setText("jLabel1");

        viewpphone.setText("jLabel1");

        viewpemail.setText("jLabel1");

        ophone.setText("jLabel1");

        viewoemail.setText("jLabel1");

        viewcstreet.setText("jLabel1");

        viewcapt.setText("jLabel1");

        viewccity.setText("jLabel1");

        viewczip.setText("jLabel1");

        viewpstreet.setText("jLabel1");

        viewpapt.setText("jLabel1");

        viewpcity.setText("jLabel1");

        viewpzip.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(viewnuid, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addComponent(viewfname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewlname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewcolname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewpphone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewpemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(viewczip, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addComponent(viewccity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewcapt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewcstreet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ophone, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addComponent(viewoemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(viewpzip, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addComponent(viewpcity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewpapt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewpstreet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(viewnuid)
                .addGap(28, 28, 28)
                .addComponent(viewfname)
                .addGap(26, 26, 26)
                .addComponent(viewlname)
                .addGap(28, 28, 28)
                .addComponent(viewcolname)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewpphone)
                    .addComponent(ophone))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewpemail)
                    .addComponent(viewoemail))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewcstreet)
                    .addComponent(viewpstreet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewcapt)
                    .addComponent(viewpapt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewccity)
                    .addComponent(viewpcity))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewpzip)
                    .addComponent(viewczip))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Currcity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Currentaddr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Currzip, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textcurrcity)
                                    .addComponent(textcurrzip)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Currapt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textcurrapt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Currstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textcurrstreet, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Firstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Lastname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Collegename, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Personalphone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                            .addComponent(PersonalEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(NUID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textNUID)
                                            .addComponent(textfirstname)
                                            .addComponent(textlastname)
                                            .addComponent(textcollgname)
                                            .addComponent(textpersphone)
                                            .addComponent(textpersemail, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))))))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Officephone, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Officeemail, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textofficeemail, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textofficephone, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Perstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Peraddr, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Permapt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Permcity, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Permzip, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textpermcity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(textpermapt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textpermstreet)
                                    .addComponent(textpermzip))))
                        .addGap(48, 48, 48))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NUID)
                            .addComponent(textNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Firstname)
                            .addComponent(textfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lastname)
                            .addComponent(textlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Collegename)
                            .addComponent(textcollgname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Personalphone)
                            .addComponent(Officephone)
                            .addComponent(textpersphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textofficephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PersonalEmail)
                            .addComponent(textpersemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Officeemail)
                            .addComponent(textofficeemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Currentaddr)
                            .addComponent(Peraddr))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Currstreet)
                                    .addComponent(Perstreet)
                                    .addComponent(textcurrstreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addComponent(Currapt))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textpermstreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textcurrapt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Permapt)
                                    .addComponent(textpermapt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Currcity)
                            .addComponent(textcurrcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Permcity)
                            .addComponent(textpermcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textcurrzip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Currzip)
                    .addComponent(Permzip)
                    .addComponent(textpermzip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(Savebutton)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SavebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebuttonActionPerformed
        // TODO add your handling code here:
        String nuid = textNUID.getText();
        //long nuid = Long.valueOf(textNUID.getText());
        String ftname = textfirstname.getText();
        String lname = textlastname.getText();
        String collname = textcollgname.getText();
        
        String Pphone = textpersphone.getText();
        String Pemail = textpersemail.getText();
        String Ophone = textofficephone.getText();
        String Oemail = textofficeemail.getText();
        
        String Currstreet = textcurrstreet.getText();
        String Currapt = textcurrapt.getText();
        String Currcity = textcurrcity.getText();
        String Currzipcode = textcurrzip.getText();
        
        String Perstreet = textpermstreet.getText();
        String Perapt = textpermapt.getText();
        String Percity = textpermcity.getText();
        String Perzipcode = textpermzip.getText();
        
        this.Person.setNUID((int) Long.parseLong(nuid));
        this.Person.setFirstName(ftname);
        this.Person.setLastName(lname);
        this.Person.setCollegeName(collname);
        
        Address addr = this.Person.getAddress();
        ContactInfo con = this.Person.getContacInfo();
        
        con.setPersonalphoneNo(Long.parseLong(Pphone));
        con.setPersonalemail(Pemail);
        
        con.setOfficephone(Long.parseLong(Ophone));
        con.setOfficeemail(Oemail);
        
        addr.setCurrstreetName(Currstreet);
        addr.setCurrapartno(Integer.parseInt(Currapt));
        addr.setCurrcity(Currcity);
        addr.setCurrzipcode(Long.parseLong(Currzipcode));
        
        addr.setPerstreetName(Perstreet);
        addr.setPerapartno(Integer.parseInt(Perapt));
        addr.setPercity(Percity);
        addr.setPerzipcode(Long.parseLong(Perzipcode));
        
        
        JOptionPane.showMessageDialog(null,"Saved Successfully!");
        Display();
        
        
        
        
    }//GEN-LAST:event_SavebuttonActionPerformed
    public void Display(){
        viewnuid.setText(String.valueOf(this.Person.getNUID()));
        viewfname.setText(this.Person.getFirstName());
        viewlname.setText(this.Person.getLastName());
        viewcolname.setText(this.Person.getCollegeName());
        
        viewpphone.setText(String.valueOf(this.Person.getContacInfo().getPersonalphoneNo()));
        viewpemail.setText(this.Person.getContacInfo().getPersonalemail());
        
        ophone.setText(String.valueOf(this.Person.getContacInfo().getOfficephone()));
        viewoemail.setText(this.Person.getContacInfo().getOfficeemail());
        
        viewcstreet.setText(this.Person.getAddress().getCurrstreetName());
        viewcapt.setText(String.valueOf(this.Person.getAddress().getCurrapartno()));
        viewccity.setText(this.Person.getAddress().getCurrcity());
        viewczip.setText(String.valueOf(this.Person.getAddress().getCurrzipcode()));
        
        viewpstreet.setText(this.Person.getAddress().getPerstreetName());
        viewpapt.setText(String.valueOf(this.Person.getAddress().getPerapartno()));
        viewpcity.setText(this.Person.getAddress().getPercity());
        viewpzip.setText(String.valueOf(this.Person.getAddress().getPerzipcode()));
        
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Collegename;
    private javax.swing.JLabel Currapt;
    private javax.swing.JLabel Currcity;
    private javax.swing.JLabel Currentaddr;
    private javax.swing.JLabel Currstreet;
    private javax.swing.JLabel Currzip;
    private javax.swing.JLabel Firstname;
    private javax.swing.JLabel Lastname;
    private javax.swing.JLabel NUID;
    private javax.swing.JLabel Officeemail;
    private javax.swing.JLabel Officephone;
    private javax.swing.JLabel Peraddr;
    private javax.swing.JLabel Permapt;
    private javax.swing.JLabel Permcity;
    private javax.swing.JLabel Permzip;
    private javax.swing.JLabel PersonalEmail;
    private javax.swing.JLabel Personalphone;
    private javax.swing.JLabel Perstreet;
    private javax.swing.JButton Savebutton;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel ophone;
    private javax.swing.JTextField textNUID;
    private javax.swing.JTextField textcollgname;
    private javax.swing.JTextField textcurrapt;
    private javax.swing.JTextField textcurrcity;
    private javax.swing.JTextField textcurrstreet;
    private javax.swing.JTextField textcurrzip;
    private javax.swing.JTextField textfirstname;
    private javax.swing.JTextField textlastname;
    private javax.swing.JTextField textofficeemail;
    private javax.swing.JTextField textofficephone;
    private javax.swing.JTextField textpermapt;
    private javax.swing.JTextField textpermcity;
    private javax.swing.JTextField textpermstreet;
    private javax.swing.JTextField textpermzip;
    private javax.swing.JTextField textpersemail;
    private javax.swing.JTextField textpersphone;
    private javax.swing.JLabel viewcapt;
    private javax.swing.JLabel viewccity;
    private javax.swing.JLabel viewcolname;
    private javax.swing.JLabel viewcstreet;
    private javax.swing.JLabel viewczip;
    private javax.swing.JLabel viewfname;
    private javax.swing.JLabel viewlname;
    private javax.swing.JLabel viewnuid;
    private javax.swing.JLabel viewoemail;
    private javax.swing.JLabel viewpapt;
    private javax.swing.JLabel viewpcity;
    private javax.swing.JLabel viewpemail;
    private javax.swing.JLabel viewpphone;
    private javax.swing.JLabel viewpstreet;
    private javax.swing.JLabel viewpzip;
    // End of variables declaration//GEN-END:variables
}
