/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.Medicine;
import Model.Observation;
import java.util.ArrayList;

/**
 *
 * @author jeelkanzaria
 */
public class MedicineAssignJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicineAssignJPanel
     */
    private Application application;
    
    public MedicineAssignJPanel() {
        initComponents();
    }

    MedicineAssignJPanel(Application application) {
      initComponents();  
      this.application = application;
      
      populateDropdown();
    }
    
    public void populateDropdown(){
        
        ArrayList<Medicine> medicines = this.application.getCatalog().getMedicineList();
        
        ArrayList<Observation> observation = this.application.getHistory().getVitalSignHistory();
        
        for(Observation o: observation){
            observationBox.addItem(o);
        }
        
        for(Medicine med: medicines){
            medicineBox.addItem(med);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medicineBox = new javax.swing.JComboBox();
        observationBox = new javax.swing.JComboBox();
        btnAssign = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add(medicineBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 160, -1));

        add(observationBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 170, -1));

        btnAssign.setText("ASSIGN");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        
        //assign selected medicine object to observation
        
        Observation o = (Observation) observationBox.getSelectedItem();
        Medicine m = (Medicine) medicineBox.getSelectedItem();
        
        o.setMedication(m);
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JComboBox medicineBox;
    private javax.swing.JComboBox observationBox;
    // End of variables declaration//GEN-END:variables
}
